# Uncomment this line to define a global platform for your project

platform :ios, '9.0'

workspace 'ALTableView'
use_frameworks!

def app_pods
    project 'TestALTableView/TestALTableView.xcodeproj'
    pod 'SwipeCellKit', '2.5.0'
end

def framework_pods
    project 'ALTableView/ALTableView.xcodeproj'
end

target 'ALTableView' do
    
    framework_pods
    # Pods for ALTableView
    
    target 'ALTableViewTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end

target 'TestALTableView' do
    app_pods
end
